Add Homoglyphs detection in Minder
stacklok/minder pull request #2312
Opened 2024-02-08 21:12 UTC by teodor-yanev

Please refer to https://github.com/stacklok/minder/issues/2121 for a full description of the work covered in this PR. There will be a second short one for adding the rule types and a profile.

Reference to the PR and repo used for testing the feature: https://github.com/teodor-yanev/a-testrepo/pull/1

A couple of notes here regarding the implementation:
1) Considering the ongoing work (https://github.com/stacklok/minder/pull/2171) and the tightly coupled (to the "vulncheck" dependency checks for ecosystems functionality) way of review related calls and string constants, I decided to opt-in for an "extract and refactor" approach which can be seen in "reviewer.go" and the related functions and files. After we reach a consensus on a way to generalise these calls, we can come back to this work and address the necessary changes.

2) Two rule types instead of one with parameters: an entirely subjective decision, I see this approach giving more flexibility when we want to further customise each individual rule.

3) Two evaluators behind one "main" 'Homoglyphs' evaluator: The Homoglyphs evaluator presents a type field which gives as a direction which which functionality we need, that's it. They are two for now, but might be more in the future. While they are still classified under the same type of "Evaluator", they are still two separate logical entities, providing a different set of results, making decisions based on different parameters.

2024-02-08 21:15 UTC, JAORMX commented
6k PR daaaaaaaaaaamn

2024-02-09 12:33 UTC, dmjb requested changes

2024-02-09 19:12 UTC, teodor-yanev commented on internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go
> +func (mse *MixedScriptsEvaluator) Eval(ctx context.Context, _ map[string]any, res *engif.Result) error {
Thanks for the descriptive suggestion and the discussion that followed in Slack! 
I've addressed your comments.

2024-02-11 13:41 UTC, dmjb approved these changes

2024-02-11 19:01 UTC, merged