Ensure rule type `guidance` is valid markdown.
stacklok/minder pull request #4292
Opened 2024-08-27 15:15 UTC by blkt

# Summary

We're currently treating `guidance` as a plain string, storing it unmodified.

This change introduces some controls ensuring that guidance is valid markdown before storing it in the database. Since any valid UTF-8 string is valid markdown, the check is a bit redundant at the moment and ensures that it is parseable and renderable as HTML.

Additionally, we limit its size to 10kB, which is far more than enough given the current rule types have a `guidance` field shorter than 1kB.

Fixes #4286

## Change Type

- [ ] Bug fix (resolves an issue without affecting existing features)
- [X] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [ ] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

Manual tests.

# Review Checklist:

- [X] Reviewed my own code for quality and clarity.
- [X] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [X] Checked that related changes are merged.

2024-08-27 19:41 UTC, rdimitrov submitted a review, later dismissed

2024-08-28 05:39 UTC, JAORMX requested changes
Should this also cover `UpdateRuleType?

2024-08-28 05:39 UTC, JAORMX commented on internal/controlplane/handlers_ruletype.go
> +		return nil, status.Errorf(
Should this be a user-facing issue? We have a `UserVisibleError` wrapper that allows for this.

2024-08-28 05:39 UTC, JAORMX commented on internal/controlplane/handlers_ruletype.go
> +		)
Should this be a user-facing issue? We have a UserVisibleError wrapper that allows for this.

2024-08-28 08:33 UTC, blkt commented
Thanks for catching that @JAORMX

2024-08-28 08:43 UTC, JAORMX approved these changes

2024-08-28 09:29 UTC, merged